### ISSUE TITLE
How to identify location

### ISSUE THREAD

**Issue by vinayodela** [ashaywalke/resume-parser#2]
Can you please help me with method to identify location from resume

**Comment by ashaywalke** [comment]
Hey @vinayodela, You can do that with a simple regex expression. 
One example can be : 
\d+[ ](?:[A-Za-z0-9.-]+[ ]?)+(?:Avenue|Lane|Road|Boulevard|Drive|Street|Ave|Dr|Rd|Blvd|Ln|St).?

**Comment by vinayodela** [comment]
Hi Ashaywalke thanks for reply,
I used this code like this: 
def extract_location(string):
    r = re.compile(r'\d+[ ](?:[A-Za-z0-9.-]+[ ]?)+(?:Avenue|Lane|Road|Boulevard|Drive|Street|Ave|Dr|Rd|Blvd|Ln|St).?')
    location = r.findall(string)
    return location

But still i was unable to return location from the resume file, can you please help me

**Comment by vinayodela** [comment]
I was unable to parse the .doc/.docx file Ashaywalke, can you please help me

**Comment by ashaywalke** [comment]
Hey @vinayodela, You cannot find addresses with 100% accuracy. I'd suggest to try testing it on a variety of resumes and not on only one as the regex expression was written to facilitate US addresses and not Indian addresses. Furthermore, you can find more information on how to parse addresses here. https://stackoverflow.com/questions/11456670/regular-expression-for-address-field-validation

**Comment by vinayodela** [comment]
Thanks ashaywalke this helped me a lot

**Comment by vinayodela** [comment]
I was unable to parse doc/docx resume, can you please suggest

**Comment by ashaywalke** [comment]
Hey, So in my code the resume used is a text pdf as in the pdf from which extracting text is very easy. And the text in the pdf is converted to a string. Now what I'd suggest you is to convert the text present in your doc/docx resume to a python string and then pass it on the code. You can find on StackExchange as to how to convert a doc/docx file into a python string. The code written works only on pdf as I used a pdf-string converter.
